# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-rpncalc

# >> macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude      ^libc|libdl|libm|libpthread|libpython3.8m|libpython3.4m|python|env|libutil.*$
%define pythonver               python3.11
%define rpncalcver              harbour-rpncalc
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:        A RPN Calculator for Sailfish
Version:        2.5.1
Release:        0
Group:          Qt/Qt
License:        GPL
URL:            https://github.com/lainwir3d/sailfish-rpn-calculator
Source0:        %{name}-%{version}.tar.bz2
Source100:      harbour-rpncalc.yaml
Requires:       sailfish-version >= 5.1
Requires:       sailfishsilica-qt5 >= 0.10.9
Requires:       pyotherside-qml-plugin-python3-qt5 >= 1.3.0
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  python3-base
BuildRequires:  python3-devel
BuildRequires:  python3-wheel
BuildRequires:  python3-wheel-tools

%description
Full symbolic RPN calculator. Read http://en.wikipedia.org/wiki/Reverse_Polish_notation if you want to know more about RPN calculators.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
echo %_builddir

#%{__cp}
#cp -r /home/mersdk/share/projects/Qt/sailfish-rpn-calculator/common/python_modules_src %_builddir/
cp -r ./.sfdk/src/sailfish-rpn-calculator/common/python_modules_src %_builddir/
cd python_modules_src/

tar xvf fastcache-1.1.0.tar.gz
cd fastcache-1.1.0
python3 setup.py build
cd ..

#tar xvf numpy-1.9.2.tar.gz
#cd numpy-1.9.2
#python3 setup.py build
#cd ..

tar xvf sympy-1.14.0.tar.gz
cd sympy-1.14.0
python3 setup.py build
cd ..

#tar xvf mpmath-1.4.1.tar.gz
wheel unpack mpmath-1.4.1-py3-none-any.whl
#cd mpmath-1.4.1
#python3 setup.py build
#cd ..

#tar xvf pyparsing-3.3.2.tar.gz
wheel unpack pyparsing-3.3.2-py3-none-any.whl
#cd pyparsing-3.3.2
#python3 setup.py build
#cd ..

#tar xvf dice-4.0.0.tar.gz
wheel unpack dice-4.0.0-py3-none-any.whl
#cd dice-4.0.0
#python3 setup.py build
#cd ..

cd ..
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
cd python_modules_src/

cd fastcache-1.1.0
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
cd ..

#cd numpy-1.9.2
#python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
#cd ..

cd sympy-1.14.0
python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
cd ..

cd mpmath-1.4.1
#python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
mkdir -p %{buildroot}/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/mpmath
ls
cp -r ./mpmath %buildroot/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/
mkdir -p %{buildroot}/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/mpmath-1.4.1.dist-info
cp -r ./mpmath-1.4.1.dist-info %buildroot/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/
cd ..

cd pyparsing-3.3.2
#python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
mkdir -p %{buildroot}/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/pyparsing
cp -r ./pyparsing %buildroot/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/
mkdir -p %{buildroot}/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/pyparsing-3.3.2.dist-info
cp -r ./pyparsing-3.3.2.dist-info %buildroot/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/
cd ..

cd dice-4.0.0
#python3 setup.py install --root=%{buildroot} --prefix=%{_datadir}/%{name}/
mkdir -p %{buildroot}/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/dice
cp -r ./dice %buildroot/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/
mkdir -p %{buildroot}/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/dice-4.0.0.dist-info
cp -r ./dice-4.0.0.dist-info %buildroot/%{_datadir}/%{name}/lib/%{pythonver}/site-packages/
cd ..

rm -rf %{buildroot}/%{_datadir}/%{name}/share
rm -rf %{buildroot}/%{_datadir}/%{name}/bin

cd ..
echo $(pwd)
echo $(ls)

#cp /usr/lib/libpython3.8m.so.1.0 %{buildroot}/%{_datadir}/%{name}/lib/
#cp %{_libdir}/libpython3.8m.so.1.0 %{buildroot}/%{_datadir}/%{name}/lib/
#cp /lib/libutil.so.1 %{buildroot}/%{_datadir}/%{name}/lib/libutil.so.1
#cp %{_lib}/libutil.so.1 %{buildroot}/%{_datadir}/%{name}/lib/libutil.so.1

#install -D -m 755 --target-directory %{buildroot}%{_datadir}/%{name}/lib/ \
#    /usr/lib/libFooBar.so.1.2.3
#https://forum.sailfishos.org/t/sdk-multiple-build-steps-qmake-and-cmake/6927/2

# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/icons/hicolor/108x108/apps/%{name}.png
%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
%{_datadir}/icons/hicolor/172x172/apps/%{name}.png
%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
%{_datadir}/applications/%{name}.desktop
%{_datadir}/%{name}
%{_bindir}
# >> files
# << files
